"""added is media to post

Revision ID: 03b3d2a0275c
Revises: 6baf5e4675e9
Create Date: 2026-05-29 14:55:55.635337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b3d2a0275c'
down_revision: Union[str, Sequence[str], None] = '6baf5e4675e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_media', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_media')
    # ### end Alembic commands ###
