"""auto generate vote

Revision ID: 6baf5e4675e9
Revises: 66cd122c8824
Create Date: 2026-05-29 14:50:13.723819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baf5e4675e9'
down_revision: Union[str, Sequence[str], None] = '66cd122c8824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('post', sa.Column('context', sa.String(), nullable=False))
    op.add_column('post', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post', 'rating')
    op.drop_column('post', 'context')
    op.drop_table('votes')
    # ### end Alembic commands ###
